### ISSUE TITLE
Auto-save fixes suggestions

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-engine-ui#241]
In my opinion, the current implementation is wrong. What we should do instead is:

- store all modified data in an object
- periodically PATCH using that object and reset it
- make sure the interval is not super fast.. we want to prevent huge data loss, not to spam the API

We can PATCH every 30 seconds or even more.

cc @rootelement @jmgasper

**Comment by jmgasper** [comment]
@ThomasKranitsas - Periodically PATCH'ing and resetting may not be the best approach, if the data we get back is outdated because ES isn't updated properly.  I don't see how our implementation is necessarily *wrong*, other than maybe for the specification fields, which I've logged a separate issue about already.
