### ISSUE TITLE
Project search improvement

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-engine-ui#669]
Currently project search is not using the project api's search capabilities e.g. any thing that goes in double quotes, should result in unique project if user is searching for a project with exact project title.

**Comment by acshields** [comment]
I do think this is an issue that needs to get resolved, but may require further conversation. Re: our conversation this morning, I agree with you that Connect should provide the project search/navigation capabilities and not the Work Manager.

If we pursue the Connect-embedded Work Manager screens for challenge set-up screens then I think long-term the project search functionality within the Work Manager app will not need to be supported, and potentially removed.

Instead of investing resources into fixing this in the Work Manager, I wonder whether we should look at how best to enable this through Connect. What are your thoughts?

**Comment by vikasrohit** [comment]
I got it fixed with my ramp up investigations with the app.
