### ISSUE TITLE
Timeline Edits Not Persisting

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/challenge-engine-ui#678]
Observed Behavior: When a user edits a timeline template in the Work Manager, the changes are not stored and are not reflected on the timeline Gantt chart.

Expected Behavior: When a user edits a timeline template, the changes should be stored and should be reflected on the timeline Gantt chart.

**Comment by vikasrohit** [comment]
Yep, it is a known issue. Do you think we need it for the v1?

**Comment by vikasrohit** [comment]
@acshields timeline is saved when user hits the global Save button as I described in https://github.com/topcoder-platform/challenge-engine-ui/issues/668#issuecomment-640559234. So, it is mainly we need to reflect the updates in the Gantt chart as well and stop reseting the phases to server immediately after `Reset Phases` button is clicked.

**Comment by vikasrohit** [comment]
@acshields I have applied a fix for it. Now it should be properly updating the timeline in the gantt chart as well when user is updating the timeline via Edit mode.

@drasticdpk this should be in dev in 15 minutes. As testing guide, we should also verify that there is no regression for https://github.com/topcoder-platform/challenge-engine-ui/issues/218 because I have remove [some code](https://github.com/topcoder-platform/challenge-engine-ui/pull/219) which was introduced to fix https://github.com/topcoder-platform/challenge-engine-ui/issues/218. In my understanding that issue was happening because earlier it used to auto saving the timelines as well, however, with https://github.com/topcoder-platform/challenge-engine-ui/issues/659, auto saving was disabled for all fields except the specification.

**Comment by drasticdpk** [comment]
Verified on Dev env
![image](https://user-images.githubusercontent.com/25297859/84349025-2b897080-abd6-11ea-93f8-5ca3a85ea875.png)
![image](https://user-images.githubusercontent.com/25297859/84349072-45c34e80-abd6-11ea-986d-85a3d6baa14a.png)
