### ISSUE TITLE
No projects shown in the landing page

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-engine-ui#690]
1. Login as `jcori`
2. Go to https://challenges.topcoder-dev.com/
3. Observe

### Issue / Actual behavior
The page says `No project selected. Select one below` but no projects show up. I need to toggle the `My Projects` checkbox off and then back on to see the projects.

### Expected behavior

The list of projects should show up

**Comment by vikasrohit** [comment]
As we don't have any formal features planned for the application yet for the initial release, I optimized the application for first use case of topcoder employees using the application to create challenges. And to do that, I move the list of projects from the left panel to the central panel because it was becoming very difficult for me to locate my project from the left panel. 
Further, it does not make sense to repeat the project listing page in challenge manager as well while we have that in Connect and these two apps are to be used in tandem to work through challenge lifecycle. 
So, now it requires the user to first search the project and then select the project. Selecting a project was always required to show the list of challenges for a project.
We will see if we really get some feature to be built into app where it needs the list of projects to be shown on the landing page.
I have also made many improvements in the project search considering the primary use case of the first release.
> User can change the project by searching the project in the search bar located just below the top bar in the right panel. User can also enter the project id or project name (in double quotes) to find the exact project.

Source: https://github.com/topcoder-platform/challenge-engine-ui/wiki/Known-rules-facts-for-MVP-v1

**Comment by vikasrohit** [comment]
@ThomasKranitsas @acshields I just reintroduced the project listing on page for now because it seems like users are expecting the project listing to be part of CM which ideally should not be. We can decide later if we need to keep it or not.

**Comment by ThomasKranitsas** [comment]
It seems to be working fine now. We can close this issue.

**Comment by drasticdpk** [comment]
Verified on dev env. 
Yes it is working fine as expected. 
Note : Better not call challenge api if we are not binding that data in initial page load event.
Correct me if i am wrong and let me know it has to create new issue. cc @vikasrohit 
![image](https://user-images.githubusercontent.com/25297859/84932642-5141d880-b0f4-11ea-83cf-569c3760c8c2.png)

**Comment by vikasrohit** [comment]
No need for separate issue. I think we can ignore the extra api call for now.
