### ISSUE TITLE
The label and placeholder text is not identical.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/challenge-engine-ui#696]
**To Reproduce / Actual Behavior**

1. Go to 'https://challenges.topcoder-dev.com/'
2. Observe the label and placeholder of project switch/search box.

**Expected behavior**
The label and placeholder text of  should be identical i.e either switch projects or search projects. 

**Screenshots or Video**
![image](https://user-images.githubusercontent.com/25297859/84756822-07b59880-afe3-11ea-85ab-dc33bafb38e3.png)

**Comment by vikasrohit** [comment]
@drasticdpk the inside text is placeholder which does not need to be in same case as we have for label because placeholder is meant to be descriptive text around the field. However, I am updating the placeholder text to `Search projects (Enter project id or project title in double quotes or any text from project)` to be much more descriptive for now.

**Comment by drasticdpk** [comment]
Verified in Dev Env :
Reference Project :
https://challenges.topcoder-dev.com/projects/16573/challenges
https://connect.topcoder-dev.com/projects/16573/scope
![image](https://user-images.githubusercontent.com/25297859/85011932-fb1b7680-b181-11ea-9c90-be3a0b235541.png)
